[versions]
# https://mvnrepository.com/artifact/org.yaml/snakeyaml
snakeyaml = "2.2"
# https://mvnrepository.com/artifact/org.apache.derby/derby
derby = "10.16.1.1"
# https://mvnrepository.com/artifact/org.slf4j/slf4j-api
slf4j = "2.0.13"
# https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
logback = "1.5.6"

[libraries]
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
derby = { module = "org.apache.derby:derby", version.ref = "derby" }
derbytools = { module = "org.apache.derby:derbytools", version.ref = "derby" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
